"use client";
import { useEffect, useRef } from "react";

// Real GLBs generated by three.ws free API
export const CLAWRENA_GLB = "https://pub-2534e921bf9c4314addcd4d8a6e98b7b.r2.dev/forge/e4238875c2f2/aa39815c-4363-4c97-ab3d-d33c94c85a16.glb";
export const COIN_GLB = "https://storage.googleapis.com/three-ws-avatar-reconstructions/raw-meshes/trellis/ad7cd57e-703b-4b5c-96a8-dd96364c5af2.glb";

interface ModelViewerProps {
  src: string;
  alt?: string;
  height?: string;
  autoRotate?: boolean;
  cameraControls?: boolean;
  environmentImage?: string;
  exposure?: string;
  shadowIntensity?: string;
  poster?: string;
}

export function ModelViewer({
  src,
  alt = "3D Model",
  height = "380px",
  autoRotate = true,
  cameraControls = true,
  exposure = "1.2",
  shadowIntensity = "1",
}: ModelViewerProps) {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Dynamically import model-viewer web component
    import("@google/model-viewer").catch(() => {
      // fallback — load via CDN if package fails
      if (!document.querySelector('script[data-mv]')) {
        const s = document.createElement("script");
        s.setAttribute("data-mv", "1");
        s.type = "module";
        s.src = "https://ajax.googleapis.com/ajax/libs/model-viewer/3.5.0/model-viewer.min.js";
        document.head.appendChild(s);
      }
    });
  }, []);

  return (
    <div ref={ref} style={{ width: "100%", height }} className="relative rounded-2xl overflow-hidden bg-[#07080b]">
      {/* @ts-expect-error model-viewer is a custom element */}
      <model-viewer
        src={src}
        alt={alt}
        auto-rotate={autoRotate ? "" : undefined}
        camera-controls={cameraControls ? "" : undefined}
        exposure={exposure}
        shadow-intensity={shadowIntensity}
        style={{ width: "100%", height: "100%", background: "transparent" }}
        environment-image="neutral"
        tone-mapping="commerce"
      >
        <div slot="poster" className="flex items-center justify-center h-full">
          <div className="size-8 border-2 border-[#22c7b8] border-t-transparent rounded-full animate-spin" />
        </div>
        {/* @ts-expect-error model-viewer is a custom element */}
      </model-viewer>
      {/* Teal glow overlay */}
      <div className="pointer-events-none absolute inset-0 rounded-2xl" style={{ boxShadow: "inset 0 0 60px -20px rgba(34,199,184,0.15)" }} />
    </div>
  );
}
