"use client";
import { useEffect, useRef, useState } from "react";

// Real GLBs generated by three.ws /api/3d/generate
export const CLAWRENA_GLB =
  "https://pub-2534e921bf9c4314addcd4d8a6e98b7b.r2.dev/forge/e4238875c2f2/aa39815c-4363-4c97-ab3d-d33c94c85a16.glb";
export const COIN_GLB =
  "https://storage.googleapis.com/three-ws-avatar-reconstructions/raw-meshes/trellis/ad7cd57e-703b-4b5c-96a8-dd96364c5af2.glb";

interface ThreeViewerProps {
  src: string;
  height?: string;
  background?: string;
  autoRotate?: boolean;
  alt?: string;
}

export function ThreeViewer({
  src,
  height = "400px",
  background = "#07080b",
  autoRotate = true,
  alt = "3D Model",
}: ThreeViewerProps) {
  const [ready, setReady] = useState(false);
  const registered = useRef(false);

  useEffect(() => {
    if (registered.current) return;
    registered.current = true;
    // Import the lightweight viewer — registers <three-ws-viewer> custom element
    import("@three-ws/avatar/viewer")
      .then(() => setReady(true))
      .catch(() => {
        // Fallback: CDN script
        const s = document.createElement("script");
        s.type = "module";
        s.src = "https://cdn.jsdelivr.net/npm/@three-ws/avatar@latest/dist/index.mjs";
        s.onload = () => setReady(true);
        document.head.appendChild(s);
      });
  }, []);

  return (
    <div
      className="relative w-full overflow-hidden rounded-2xl"
      style={{ height, background }}
    >
      {/* Teal glow border effect */}
      <div
        className="pointer-events-none absolute inset-0 z-10 rounded-2xl"
        style={{ boxShadow: "inset 0 0 80px -30px rgba(34,199,184,0.2), 0 0 60px -20px rgba(34,199,184,0.15)" }}
      />

      {!ready && (
        <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 z-20">
          <div className="size-10 rounded-full border-2 border-[#22c7b8] border-t-transparent animate-spin" />
          <p className="text-xs text-[#8b909a]">Loading 3D model…</p>
        </div>
      )}

      {ready && (
        // @ts-expect-error three-ws-viewer is a custom element registered by @three-ws/avatar
        <three-ws-viewer
          src={src}
          background={background}
          alt={alt}
          auto-rotate={autoRotate ? "true" : "false"}
          style={{ width: "100%", height: "100%", display: "block" }}
        />
      )}
    </div>
  );
}
